---
env:
  DOCKER_IMAGE=minddocdev/hubot
  DOCKER_TAG=0.1.9

services:
  - docker

stages:
  - build
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: lint
      script:
        # Lint the Dockerfile
        - docker run -it --rm -v "${PWD}/Dockerfile:/Dockerfile:ro" redcoolbeans/dockerlint
    - stage: deploy
      script:
        # Build the docker image
        - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
        # Tag the docker image
        - docker tag $DOCKER_IMAGE:$DOCKER_TAG $DOCKER_IMAGE:latest
        # Push the docker image to Docker Hub
        - docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
        - docker push $DOCKER_IMAGE:$DOCKER_TAG
        - docker push $DOCKER_IMAGE:latest
